name: shoot to interwebz

# Controls when the workflow will run
on:
  # Triggers the workflow on push
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
            
      - name: create .ssh dir
        run: mkdir ~/.ssh 

      - name: put secret stuff into file
        run: echo """${{ secrets.KEY }}""" > ~/.ssh/id_rsa      

      - name: restrict private key permissions
        run: sudo chmod 600 ~/.ssh/id_rsa     

      - name: put secret stuff into file
        run: echo """${{ secrets.KNOWN }}""" > ~/.ssh/known_hosts    

      - name: send the files to the server
        run: scp index.html cv.html photos.html amazingBeautyGiver.css ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/html

