# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: create .ssh dir
        run: mkdir .ssh 

      - name: put secret stuff into file
        run: echo """${{ secrets.KEY }}""" > ./.ssh/id_rsa      

      - name: put secret stuff into file
        run: echo """${{ secrets.KNOWN }}""" > ./.ssh/known_hosts    
      
      - name: known?
        run: ls .ssh/

      - name: scp
        run: scp index.html ${{ secrets.USER }}@${{ secrets.HOST }} ./site

